- project:
    templates:
      - openstack-cover-jobs
      - openstack-python37-jobs
      - openstack-python3-yoga-jobs
    check:
      jobs:
        - refstack-client-devstack-master:
            # Define a list of irrelevant files to use everywhere else
            irrelevant-files: &refstack-client-irrelevant-files
              - ^.*\.rst$
              - ^doc/.*$
              - ^.gitignore$
              - ^.gitreview$
        - refstack-client-devstack-wallaby:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-victoria:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-ussuri:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-train:
            irrelevant-files: *refstack-client-irrelevant-files
        - opendev-tox-docs
    gate:
      jobs:
        - refstack-client-devstack-master:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-wallaby:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-victoria:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-ussuri:
            irrelevant-files: *refstack-client-irrelevant-files
        - refstack-client-devstack-train:
            irrelevant-files: *refstack-client-irrelevant-files
        - opendev-tox-docs
    promote:
      jobs:
        - opendev-promote-docs
